### ISSUE TITLE
[Mod Support Request] - Caves and Cliffs Backport, Mowzie's Mobs, and Untamed Wilds

### ISSUE THREAD

**Issue by kraftw** [babybluetit/Xaeros-Minimap-Modded-Support#1]
### **Caves and Cliffs Backport**
**Link:** https://www.curseforge.com/minecraft/mc-mods/caves-and-cliffs-backport
**Mobs:** _3_

### **Mowzie's Mobs**
**Link:** https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs
**Mobs:** _8_

### **Untamed Wilds**
**Link:** https://www.curseforge.com/minecraft/mc-mods/untamedwilds
**Mobs:** _17_ (_88_ including all the variants)

Thank you if you do decide to implement these! These are the last in my modpack that add mobs that aren't currently supported, I really appreciate what you do!

_sorry if posted this wrong and i don't have the proper formatting, i made an account to post here so i'm not sure how to do some things_

**Comment by babybluetit** [comment]
Thanks for your request! The formatting is perfect, don't worry :)

The Caves & Cliffs mod was fairly easy to add support to so I'll upload it in the pack next week. I'll also try to add support for Mowzie's by then as well.
Untamed Wilds will take me a bit longer, but I'll start work on it soon!

**Comment by babybluetit** [comment]
I've [finished support](https://github.com/babybluetit/Xaeros-Minimap-Modded-Support/commit/5dcb06b374188a02f3141e84fc1bf9fbea3efc69) for Untamed Wilds, will upload the updated pack to curseforge later today.
