### ISSUE TITLE
[Mod Support Request] - Darker Depths - Untitled Duck Mod - Danny's Expansion

### ISSUE THREAD

**Issue by mightyjaffa12** [babybluetit/Xaeros-Minimap-Modded-Support#10]
Darker Depths 
https://www.curseforge.com/minecraft/mc-mods/darker-depths 
2 mobs 

Untitled Duck Mod
https://www.curseforge.com/minecraft/mc-mods/untitled-duck-mod-forge
2 mobs 

Danny's Expansion 
https://www.curseforge.com/minecraft/mc-mods/beta-dannys-expansion
22 mobs

**Comment by babybluetit** [comment]
Thanks for your request!

* [Added support](https://github.com/babybluetit/Xaeros-Minimap-Modded-Support/commit/505a8959acbee3614faad5b121ab156aa3716587) for Darker Depths, will upload to the curseforge page tomorrow.
* Duck mod - unfortunately, there's an issue with the entity texture not being set correctly ([see here](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap/issues/555)) so I won't be able to support the duck variants but I can use a single icon for both variants - will get on this soon.
* I will start on Danny's Expansion soon, just after I have added support for a couple of other mods!

**Comment by mightyjaffa12** [comment]
Brilliant thank you ^^

**Comment by babybluetit** [comment]
- [Added support](https://github.com/babybluetit/Xaeros-Minimap-Modded-Support/commit/6a41822bf224fb315a2c43a84bfb3b9bf79b9e16) for Danny's Expansion
- [Added support](https://github.com/babybluetit/Xaeros-Minimap-Modded-Support/commit/d7ba17f79d0143d02d0360d021f85b89f912b79f) for Untitled Duck Mod

The updated pack has just been [uploaded to CurseForge](https://www.curseforge.com/minecraft/texture-packs/xaeros-minimap-modded-support/files/3594854).
