### ISSUE TITLE
[Mod Support Request] - Creeper Overhaul

### ISSUE THREAD

**Issue by ClayBC** [babybluetit/Xaeros-Minimap-Modded-Support#18]
[* Link to the mod page](https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul)
List of mobs added (total: 15)
- Default creeper
- Badlands creeper
- Bamboo creeper
- Beach creeper
- Cave creeper
- Dark oak creeper
- Desert creeper
- Dripstone creeper
- Hills creeper
- Jungle creeper
- Mushroom creeper
- Savannah creeper
- Snowy creeper
- Swamp creeper
- Spruce creeper

**Comment by babybluetit** [comment]
Some of the creepers' faces and bodies are the same part, was curious whether you'd prefer me to use the whole body part as the icon but shrink it down a bit, or just use the face only:

![](https://i.imgur.com/lRaUTyd.png)

**Comment by ClayBC** [comment]
Hmm, I love the look of both but if I had to pick I’d say just the heads might look better.

**Comment by babybluetit** [comment]
[Added support](https://github.com/babybluetit/Xaeros-Minimap-Modded-Support/commit/e6f44a130b30cbaffda945259b1ce65895997df0) for Creeper Overhaul, download is on Curseforge :)

**Comment by docHP** [comment]
Hi I just wanted to say that it seems to have broken because the Default Creeper doesn't show up but the Creeper Overhaul does? Do you know why this might have happened?

![image](https://user-images.githubusercontent.com/44784448/216750630-afff0cfc-9f0b-455d-b135-aac5d5c7b277.png)
