### ISSUE TITLE
[Mod Support Request] Whisperwoods & Illagers+

### ISSUE THREAD

**Issue by Castlegrave** [babybluetit/Xaeros-Minimap-Modded-Support#2]
### **Whisperwoods**
**Mod** Link: https://www.curseforge.com/minecraft/mc-mods/whisperwoods
**Mobs:** 5

### **Illagers+**
**Mod** Link: https://www.curseforge.com/minecraft/mc-mods/illagers
**Mobs:** 9

I'd also like to thank you for making this resource pack, as this pack is one of the only reasons I'm still using Xaero's Minimap. This pack is amazing, and it'd be great if you could support these mods too. Thank you very much!

**Comment by babybluetit** [comment]
Hello, thank you for the kind words and I'm glad to hear you enjoy the pack!

I've just [added support](https://github.com/babybluetit/Xaeros-Minimap-Modded-Support/commit/b1df7f4d22a515b2f3cfa4894d3ba17523a3b706) for these two mods and they'll be included when I upload the pack on Friday. You can download the zip file from this repo if you want to use the pack before then.
