### ISSUE TITLE
[issue] copper golem icon too large

### ISSUE THREAD

**Issue by Wedge1453** [babybluetit/Xaeros-Minimap-Modded-Support#24]
![2022-02-08_12 12 18](https://user-images.githubusercontent.com/76813383/153201211-4b308ee2-8c81-459b-b34e-ce47ac5ccf67.png)

**Comment by Wedge1453** [comment]
it's from YDM's Copper Golem (1.18.1)

**Comment by babybluetit** [comment]
[YDM's CopperGolem](https://www.curseforge.com/minecraft/mc-mods/ydms-coppergolem)

**Comment by babybluetit** [comment]
[Added support](https://github.com/babybluetit/Xaeros-Minimap-Modded-Support/commit/bfc53d367c1d7659972a4647b9fdf8cb717e5a9a) for YDM's CopperGolem.
