### ISSUE TITLE
[Mod Support Request] - EXAMPLE_MOD

### ISSUE THREAD

**Issue by KMFrench1** [babybluetit/Xaeros-Minimap-Modded-Support#25]
[* Link to the mod page](https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus)
* An estimate of the number of mobs introduced by the mod (35)
* Game version 1.18.1

You already have they files set up but the model referance now has "dev." in front and a "_" needs to be removed.
Example:
old: 	"modelMainPartFieldAliases" : ["its_meow.betteranimalsplus.client.model.ModelBadger;head"
New: "modelMainPartFieldAliases" : ["dev.itsmeow.betteranimalsplus.client.model.ModelBadger;head"

**Comment by KMFrench1** [comment]
I updated the files for you. here is a link to the zip.
https://mega.nz/file/3nZTlY5Y#_ybijfc7xx-0YJ0hxyifyzr09URuhdEG1sagpzk1D3g

**Comment by babybluetit** [comment]
[Added support](https://github.com/babybluetit/Xaeros-Minimap-Modded-Support/commit/3f87e5b8c977edcc22afb565bb61629775a2090e) for Better Animals Plus.
