### ISSUE TITLE
Graveyard has added 4 new mods

### ISSUE THREAD

**Issue by KMFrench1** [babybluetit/Xaeros-Minimap-Modded-Support#27]
* Link to the mod page
* https://www.curseforge.com/minecraft/mc-mods/the-graveyard-fabric
* An estimate of the number of mobs introduced by the mod
* 4
* Game version
* 1.18.1

**Comment by babybluetit** [comment]
[Added support](https://github.com/babybluetit/Xaeros-Minimap-Modded-Support/commit/11df557d98f6570204f48d9272f2eea4349992f6) for the new mobs.
