### ISSUE TITLE
Earthbounds

### ISSUE THREAD

**Issue by KMFrench1** [babybluetit/Xaeros-Minimap-Modded-Support#29]
* Link to the mod page
* https://www.curseforge.com/minecraft/mc-mods/earthbounds
* An estimate of the number of mobs introduced by the mod
* 2
* Game version
* 1.18.1

**Comment by babybluetit** [comment]
[Added support](https://github.com/babybluetit/Xaeros-Minimap-Modded-Support/commit/a2388b2c772f6c6fe59db388159ced3f9d7bc9d7) for Earthbounds.
