### ISSUE TITLE
[Mod Support Request] - UNDEAD

### ISSUE THREAD

**Issue by haeihaiehaei** [babybluetit/Xaeros-Minimap-Modded-Support#3]
Hi, would love to have support for this:

It adds 28 mobs, more is coming in the next update.

https://www.curseforge.com/minecraft/mc-mods/theundead

**Comment by babybluetit** [comment]
Currently working on this, might take a while due to the number of mobs! :)

**Comment by babybluetit** [comment]
Added [support](https://github.com/babybluetit/Xaeros-Minimap-Modded-Support/commit/3204aca4d44ad4022559935b8ba06e6a26675ea0) for UNDEAD!
