### ISSUE TITLE
creatures-of-the-snow

### ISSUE THREAD

**Issue by KMFrench1** [babybluetit/Xaeros-Minimap-Modded-Support#33]
* Link to the mod page
* https://www.curseforge.com/minecraft/mc-mods/creatures-of-the-snow
* An estimate of the number of mobs introduced by the mod
* 5
* Game version
* 1.18.1

**Comment by babybluetit** [comment]
[Added support](https://github.com/babybluetit/Xaeros-Minimap-Modded-Support/commit/80f7c0d55d21e83c56f0821a2ace9b3bf5a5d2e6) for Creatures From The Snow.
