### ISSUE TITLE
Sorry about the all of the request

### ISSUE THREAD

**Issue by KMFrench1** [babybluetit/Xaeros-Minimap-Modded-Support#37]
Sorry about the flood of request. I just requested every mod I use. I was not in Minecraft, so I did not check them to see if they had built in support. I just went through and closed the one that already had there own support.
I am ok with it if you ignore them, but i hope you don't.

**Comment by babybluetit** [comment]
Don't worry about making too many requests! I've unfortunately been otherwise occupied, but I have more time now so I will try to work through all of your requests - and feel free to make more. 🙂
