### ISSUE TITLE
neutrino (just one more for now)

### ISSUE THREAD

**Issue by KMFrench1** [babybluetit/Xaeros-Minimap-Modded-Support#38]
* Link to the mod page
* https://www.curseforge.com/minecraft/mc-mods/neutrino
* An estimate of the number of mobs introduced by the mod
* 4
* Game version
* 1.18.1

**Comment by babybluetit** [comment]
[Added support](https://github.com/babybluetit/Xaeros-Minimap-Modded-Support/commit/c731f546ea35affd0a0926ac6229c85277c2eb57) for Neutrino.
