### ISSUE TITLE
[Mod Support Request] - Project Vibrant Journeys

### ISSUE THREAD

**Issue by haeihaiehaei** [babybluetit/Xaeros-Minimap-Modded-Support#4]
Hi would love support for this:

It adds 8 mobs.

https://www.curseforge.com/minecraft/mc-mods/project-vibrant-journeys

**Comment by babybluetit** [comment]
[Added support for Vibrant Journeys](https://github.com/babybluetit/Xaeros-Minimap-Modded-Support/commit/a679905942f58be29bf98c8cc9d301dcdf048f0c)
