### ISSUE TITLE
[Mod Support Request] - Glow Bats

### ISSUE THREAD

**Issue by wafgafs** [babybluetit/Xaeros-Minimap-Modded-Support#42]
* [Link to the mod page](https://www.curseforge.com/minecraft/mc-mods/glow-bats)
* 1
* 1.16.5

**Comment by babybluetit** [comment]
[Added support](https://github.com/babybluetit/Xaeros-Minimap-Modded-Support/commit/67b61a075ac508adc2e08f239b280aad834ce0eb) for Glow Bats.
