### ISSUE TITLE
[Mod Support Request] - Undead Expansion

### ISSUE THREAD

**Issue by haeihaiehaei** [babybluetit/Xaeros-Minimap-Modded-Support#5]
Hi, would love support for this mod:

It currently adds 3 mobs.

https://www.curseforge.com/minecraft/mc-mods/undead-expansion/files

**Comment by babybluetit** [comment]
[Added support for Undead Expansion](https://github.com/babybluetit/Xaeros-Minimap-Modded-Support/commit/a679905942f58be29bf98c8cc9d301dcdf048f0c)
