### ISSUE TITLE
[Mod Support Request] - Goodall

### ISSUE THREAD

**Issue by Nekohime1989** [babybluetit/Xaeros-Minimap-Modded-Support#69]
https://www.curseforge.com/minecraft/mc-mods/goodall
10
1.18.2 Forge/Fabric

**Comment by babybluetit** [comment]
[Support for Goodall](https://github.com/babybluetit/Xaeros-Minimap-Modded-Support/commit/dc67fea91e50209ff3cab01f3cb3b4bc96c80aae)
