### ISSUE TITLE
[Mod Support Request] - The Afterlight

### ISSUE THREAD

**Issue by wafgafs** [babybluetit/Xaeros-Minimap-Modded-Support#70]
* [Link to the mod page] (https://www.curseforge.com/minecraft/mc-mods/the-afterlight)
* 5 mobs added, checked via the wiki (https://the-afterlight.fandom.com/)
* 1.16.5 forge

**Comment by babybluetit** [comment]
[Support for The Afterlight](https://github.com/babybluetit/Xaeros-Minimap-Modded-Support/commit/561ec8df98f79314fac2e444a292a74c0df128aa)
