### ISSUE TITLE
[Mod Support Request] - Terra Incognita: The Unknown Land

### ISSUE THREAD

**Issue by haeihaiehaei** [babybluetit/Xaeros-Minimap-Modded-Support#8]
* https://www.curseforge.com/minecraft/mc-mods/terraincognita
* There are currently six variants of butterflies:

    Peacock
    Brimstone
    Cabbage White
    Orange Tip
    Common Blue
    Monarch

**Comment by babybluetit** [comment]
Will get this done tomorrow!

**Comment by babybluetit** [comment]
[Added support](https://github.com/babybluetit/Xaeros-Minimap-Modded-Support/commit/26ae292a68020b180a747bbbf61fb20dcfb1ede2) for Terra Incognita.
